name: icbm2
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  alfred: ^1.1.1
  pocketbase: ^0.11.0
  dotenv: ^4.1.0
  result_type: ^0.2.0
  nyxx: ^5.1.1
  nyxx_interactions: ^4.6.0
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
